export const categories = [
  { label: 'Electronics', value: 'electronics', icon: 'zap' },
  { label: 'Furniture', value: 'furniture', icon: 'home' },
  { label: 'Clothing', value: 'clothing', icon: 'shopping-bag' },
  { label: 'Tools', value: 'tools', icon: 'tool' },
  { label: 'Decor', value: 'decor', icon: 'sun' },
  { label: 'Collectibles', value: 'collectibles', icon: 'star' },
];
export const typeOptions = [
  { label: 'Vintage', value: 'vintage' },
  { label: 'Modern', value: 'modern' },
  { label: 'Damaged', value: 'damaged' },
  { label: 'Refurbished', value: 'refurbished' },
];

export const subcategoryOptions = {
  electronics: [
    { label: 'Phone', value: 'phone' },
    { label: 'Laptop', value: 'laptop' },
    { label: 'Speaker', value: 'speaker' },
    { label: 'TV', value: 'tv' },
    { label: 'Camera', value: 'camera' },
    { label: 'Tablet', value: 'tablet' },
    { label: 'Watch', value: 'watch' },
    { label: 'Headphones', value: 'headphones' },
    { label: 'Game Console', value: 'gameConsole' },
    { label: 'Monitor', value: 'monitor' },
    { label: 'Router', value: 'router' },
    { label: 'Printer', value: 'printer' },
  ],
  furniture: [
    { label: 'Chair', value: 'chair' },
    { label: 'Table', value: 'table' },
    { label: 'Cabinet', value: 'cabinet' },
    { label: 'Sofa', value: 'sofa' },
    { label: 'Bed', value: 'bed' },
    { label: 'Desk', value: 'desk' },
    { label: 'Dresser', value: 'dresser' },
    { label: 'Bookshelf', value: 'bookshelf' },
    { label: 'Nightstand', value: 'nightstand' },
    { label: 'Coffee Table', value: 'coffeeTable' },
    { label: 'Ottoman', value: 'ottoman' },
    { label: 'Bench', value: 'bench' },
  ],
  clothing: [
    { label: 'Jacket', value: 'jacket' },
    { label: 'Shoes', value: 'shoes' },
    { label: 'Shirt', value: 'shirt' },
    { label: 'Dress', value: 'dress' },
    { label: 'Pants', value: 'pants' },
    { label: 'Hat', value: 'hat' },
    { label: 'Bag', value: 'bag' },
    { label: 'Belt', value: 'belt' },
    { label: 'Sunglasses', value: 'sunglasses' },
    { label: 'Watch', value: 'watchClothing' },
    { label: 'Jewelry', value: 'jewelry' },
    { label: 'Boots', value: 'boots' },
  ],
  tools: [
    { label: 'Power Drill', value: 'powerDrill' },
    { label: 'Wrench', value: 'wrench' },
    { label: 'Hammer', value: 'hammer' },
    { label: 'Saw', value: 'saw' },
    { label: 'Screwdriver', value: 'screwdriver' },
    { label: 'Pliers', value: 'pliers' },
    { label: 'Level', value: 'level' },
    { label: 'Tape Measure', value: 'tapeMeasure' },
    { label: 'Socket Set', value: 'socketSet' },
    { label: 'Angle Grinder', value: 'angleGrinder' },
    { label: 'Circular Saw', value: 'circularSaw' },
    { label: 'Multimeter', value: 'multimeter' },
  ],
  decor: [
    { label: 'Lamp', value: 'lamp' },
    { label: 'Clock', value: 'clock' },
    { label: 'Frame', value: 'frame' },
    { label: 'Vase', value: 'vase' },
    { label: 'Rug', value: 'rug' },
    { label: 'Mirror', value: 'mirror' },
    { label: 'Candle Holder', value: 'candleHolder' },
    { label: 'Plant Stand', value: 'plantStand' },
    { label: 'Wall Art', value: 'wallArt' },
    { label: 'Throw Pillow', value: 'throwPillow' },
    { label: 'Curtains', value: 'curtains' },
    { label: 'Bookend', value: 'bookend' },
  ],
  collectibles: [
    { label: 'Action Figure', value: 'actionFigure' },
    { label: 'Trading Card', value: 'tradingCard' },
    { label: 'Diecast Car', value: 'diecastCar' },
    { label: 'Comic Book', value: 'comicBook' },
    { label: 'Model Train', value: 'modelTrain' },
    { label: 'Vinyl Record', value: 'vinylRecord' },
    { label: 'Vintage Toy', value: 'vintageToy' },
    { label: 'Sports Memorabilia', value: 'sportsMemorabilia' },
    { label: 'Coin', value: 'coin' },
    { label: 'Stamp', value: 'stamp' },
    { label: 'Poster', value: 'poster' },
  ],
};

export const conditionOptions = {
  phone: [
    'Cracked Screen',
    'Battery Issues',
    'Water Damage',
    'No Power',
    'Broken Buttons',
    'None of the above',
  ],
  laptop: [
    'Broken Keyboard',
    'Battery Issues',
    'Overheating',
    'Screen Flicker',
    'Damaged Ports',
    'None of the above',
  ],
  speaker: [
    'No Sound',
    'Connectivity Issues',
    'Physical Damage',
    'Distorted Audio',
    'Power Failure',
    'None of the above',
  ],
  tv: [
    'Screen Damage',
    'No Power',
    'Broken Remote',
    'Color Distortion',
    'Sound Issues',
    'None of the above',
  ],
  camera: [
    'Lens Scratch',
    'Battery Failure',
    'Focus Problems',
    'Memory Error',
    'Shutter Issue',
    'None of the above',
  ],
  tablet: [
    'Cracked Screen',
    'Battery Swollen',
    'Charging Port Loose',
    'Unresponsive',
    'Overheating',
    'None of the above',
  ],
  chair: [
    'Broken Leg',
    'Worn Fabric',
    'Loose Joints',
    'Scratched Surface',
    'Missing Parts',
    'None of the above',
  ],
  table: [
    'Scratched Surface',
    'Loose Legs',
    'Water Stains',
    'Wobbly',
    'Chipped Edge',
    'None of the above',
  ],
  cabinet: [
    'Broken Hinges',
    'Scratches',
    'Missing Shelves',
    'Stuck Drawer',
    'Loose Door',
    'None of the above',
  ],
  sofa: [
    'Torn Upholstery',
    'Sagging Cushions',
    'Broken Springs',
    'Stains',
    'Faded Fabric',
    'None of the above',
  ],
  bed: [
    'Broken Slats',
    'Worn Mattress',
    'Loose Screws',
    'Squeaky',
    'Stained Headboard',
    'None of the above',
  ],
  desk: [
    'Scratched Top',
    'Broken Drawer',
    'Loose Legs',
    'Water Damage',
    'Chipped Finish',
    'None of the above',
  ],
  jacket: [
    'Torn Sleeve',
    'Missing Buttons',
    'Stained',
    'Broken Zipper',
    'Faded Color',
    'None of the above',
  ],
  shoes: [
    'Worn Soles',
    'Loose Stitching',
    'Faded Color',
    'Scuffed Surface',
    'Broken Laces',
    'None of the above',
  ],
  shirt: [
    'Torn Collar',
    'Missing Buttons',
    'Stained',
    'Faded Fabric',
    'Loose Threads',
    'None of the above',
  ],
  dress: [
    'Torn Hem',
    'Stained',
    'Missing Zipper',
    'Faded Color',
    'Loose Seams',
    'None of the above',
  ],
  pants: [
    'Torn Knee',
    'Broken Zipper',
    'Stained',
    'Faded Color',
    'Loose Waistband',
    'None of the above',
  ],
  hat: [
    'Sweat Stains',
    'Frayed Brim',
    'Faded Color',
    'Loose Threads',
    'Missing Strap',
    'None of the above',
  ],
  powerDrill: [
    'Dull Bit',
    'Motor Issues',
    'Battery Problems',
    'Chuck Slipping',
    'Broken Trigger',
    'None of the above',
  ],
  wrench: [
    'Rusty',
    'Loose Grip',
    'Bent',
    'Worn Teeth',
    'Stuck Adjustment',
    'None of the above',
  ],
  hammer: [
    'Loose Head',
    'Worn Handle',
    'Rusty',
    'Chipped Face',
    'Bent Claw',
    'None of the above',
  ],
  saw: [
    'Dull Blade',
    'Bent Teeth',
    'Broken Handle',
    'Rust',
    'Loose Guard',
    'None of the above',
  ],
  screwdriver: [
    'Stripped Tip',
    'Broken Handle',
    'Rusty',
    'Bent Shaft',
    'Worn Grip',
    'None of the above',
  ],
  pliers: [
    'Rusty',
    'Loose Joint',
    'Worn Grip',
    'Bent Jaws',
    'Spring Broken',
    'None of the above',
  ],
  lamp: [
    'Broken Bulb',
    'Damaged Shade',
    'Faulty Wiring',
    'Loose Switch',
    'Rusty Base',
    'None of the above',
  ],
  clock: [
    'Not Working',
    'Missing Hands',
    'Cracked Glass',
    'Dead Battery',
    'Damaged Frame',
    'None of the above',
  ],
  frame: [
    'Scratched',
    'Broken Glass',
    'Loose Backing',
    'Bent Edge',
    'Faded Color',
    'None of the above',
  ],
  vase: [
    'Cracked',
    'Chipped Rim',
    'Stained',
    'Broken Handle',
    'Faded Paint',
    'None of the above',
  ],
  rug: [
    'Stained',
    'Frayed Edges',
    'Faded Color',
    'Torn Fibers',
    'Odor',
    'None of the above',
  ],
  mirror: [
    'Cracked Glass',
    'Chipped Frame',
    'Hazy Surface',
    'Loose Hanging Wire',
    'Scratched',
    'None of the above',
  ],
  actionFigure: [
    'Loose/No Box',
    'Missing Accessories',
    'Paint Wear',
    'Broken Joint',
    'Yellowed Plastic',
    'None of the above',
  ],
  tradingCard: [
    'Heavy Crease',
    'Whiting on Edges',
    'Surface Scratches',
    'Off-Center Cut',
    'Water Damage',
    'None of the above',
  ],
  diecastCar: [
    'Paint Chips',
    'Bent Axle',
    'Missing Wheels',
    'Scratched Windshield',
    'Rusty Base',
    'None of the above',
  ],
  comicBook: [
    'Torn Cover',
    'Yellowed Pages',
    'Bent Corners',
    'Loose Staples',
    'Writing/Ink Marks',
    'None of the above',
  ],
  modelTrain: [
    'Derailed/Bent Frame',
    'Missing Coupler',
    'Motor Not Running',
    'Scratched Paint',
    'Broken Detail Part',
    'None of the above',
  ],
  watch: [
    'Dead Battery',
    'Scratched Crystal',
    'Broken Band',
    'Not Working',
    'Water Damage',
    'None of the above',
  ],
  headphones: [
    'No Sound',
    'Broken Cable',
    'Cracked Headband',
    'One Side Dead',
    'Loose Connection',
    'None of the above',
  ],
  gameConsole: [
    'No Power',
    'Disc Drive Broken',
    'Overheating',
    'Controller Issues',
    'HDMI Port Damaged',
    'None of the above',
  ],
  monitor: [
    'Dead Pixels',
    'No Display',
    'Flickering Screen',
    'Cracked Screen',
    'Power Issues',
    'None of the above',
  ],
  router: [
    'No WiFi Signal',
    'Power Failure',
    'Damaged Antenna',
    'Overheating',
    'Ports Not Working',
    'None of the above',
  ],
  printer: [
    'Paper Jams',
    'Ink Issues',
    'Not Printing',
    'Error Codes',
    'Damaged Tray',
    'None of the above',
  ],
  dresser: [
    'Broken Drawers',
    'Scratched Surface',
    'Loose Handles',
    'Wobbly',
    'Water Stains',
    'None of the above',
  ],
  bookshelf: [
    'Loose Shelves',
    'Scratched',
    'Wobbly',
    'Missing Back Panel',
    'Chipped Edges',
    'None of the above',
  ],
  nightstand: [
    'Broken Drawer',
    'Scratched Top',
    'Loose Legs',
    'Missing Hardware',
    'Water Rings',
    'None of the above',
  ],
  coffeeTable: [
    'Scratched Top',
    'Wobbly Legs',
    'Water Stains',
    'Chipped Edge',
    'Loose Joints',
    'None of the above',
  ],
  ottoman: [
    'Torn Fabric',
    'Worn Cushion',
    'Broken Legs',
    'Stains',
    'Faded Color',
    'None of the above',
  ],
  bench: [
    'Worn Seat',
    'Loose Joints',
    'Scratched',
    'Broken Slats',
    'Rusty Hardware',
    'None of the above',
  ],
  bag: [
    'Torn Strap',
    'Broken Zipper',
    'Stained',
    'Worn Lining',
    'Missing Hardware',
    'None of the above',
  ],
  belt: [
    'Broken Buckle',
    'Cracked Leather',
    'Holes Worn',
    'Faded',
    'Loose Stitching',
    'None of the above',
  ],
  sunglasses: [
    'Scratched Lenses',
    'Broken Frame',
    'Missing Lenses',
    'Loose Hinges',
    'Faded',
    'None of the above',
  ],
  watchClothing: [
    'Dead Battery',
    'Scratched Face',
    'Broken Band',
    'Not Working',
    'Missing Links',
    'None of the above',
  ],
  jewelry: [
    'Tarnished',
    'Missing Stones',
    'Broken Clasp',
    'Scratched',
    'Loose Setting',
    'None of the above',
  ],
  boots: [
    'Worn Soles',
    'Torn Lining',
    'Broken Zipper',
    'Scuffed',
    'Loose Stitching',
    'None of the above',
  ],
  level: [
    'Bubble Off',
    'Scratched',
    'Bent',
    'Missing End Caps',
    'Rusty',
    'None of the above',
  ],
  tapeMeasure: [
    'Broken Lock',
    'Torn Tape',
    'Rusty',
    'Stuck',
    'Missing End Hook',
    'None of the above',
  ],
  socketSet: [
    'Missing Sockets',
    'Rusty',
    'Broken Ratchet',
    'Worn Teeth',
    'Loose Handle',
    'None of the above',
  ],
  angleGrinder: [
    'Dull Disc',
    'Motor Issues',
    'Broken Guard',
    'Power Problems',
    'Worn Brushes',
    'None of the above',
  ],
  circularSaw: [
    'Dull Blade',
    'Broken Guard',
    'Motor Issues',
    'Power Problems',
    'Worn Base',
    'None of the above',
  ],
  multimeter: [
    'Broken Display',
    'Faulty Probes',
    'Not Reading',
    'Damaged Case',
    'Battery Issues',
    'None of the above',
  ],
  candleHolder: [
    'Rusty',
    'Tarnished',
    'Cracked',
    'Missing Base',
    'Bent',
    'None of the above',
  ],
  plantStand: [
    'Wobbly',
    'Rusty',
    'Scratched',
    'Missing Shelf',
    'Bent Legs',
    'None of the above',
  ],
  wallArt: [
    'Faded',
    'Torn',
    'Broken Frame',
    'Water Damage',
    'Scratched',
    'None of the above',
  ],
  throwPillow: [
    'Torn',
    'Stained',
    'Faded',
    'Loose Seams',
    'Flat Filling',
    'None of the above',
  ],
  curtains: [
    'Torn',
    'Faded',
    'Missing Hooks',
    'Stained',
    'Loose Hems',
    'None of the above',
  ],
  bookend: [
    'Scratched',
    'Bent',
    'Rusty',
    'Missing Base',
    'Chipped',
    'None of the above',
  ],
  vinylRecord: [
    'Scratches',
    'Warped',
    'Cracked',
    'Worn Grooves',
    'Missing Sleeve',
    'None of the above',
  ],
  vintageToy: [
    'Missing Parts',
    'Paint Wear',
    'Broken',
    'Yellowed',
    'No Box',
    'None of the above',
  ],
  sportsMemorabilia: [
    'Faded',
    'Torn',
    'Stained',
    'Missing Signature',
    'Damaged Frame',
    'None of the above',
  ],
  coin: [
    'Scratched',
    'Tarnished',
    'Bent',
    'Worn',
    'Discolored',
    'None of the above',
  ],
  stamp: [
    'Torn',
    'Faded',
    'Missing Perforations',
    'Stained',
    'Creamed',
    'None of the above',
  ],
  poster: [
    'Torn',
    'Faded',
    'Creased',
    'Tape Marks',
    'Water Damage',
    'None of the above',
  ],
};