export const basePrices = {
  // Average resale values in good condition
  phone: 250,
  laptop: 500,
  speaker: 80,
  tv: 300,
  camera: 400,
  tablet: 200,
  chair: 40,
  table: 100,
  cabinet: 80,
  sofa: 150,
  bed: 200,
  desk: 120,
  jacket: 40,
  shoes: 50,
  shirt: 15,
  dress: 40,
  pants: 30,
  hat: 15,
  powerDrill: 60,
  wrench: 15,
  hammer: 15,
  saw: 30,
  screwdriver: 10,
  pliers: 15,
  lamp: 25,
  clock: 20,
  frame: 15,
  vase: 20,
  rug: 30,
  mirror: 25,
  actionFigure: 45,
  tradingCard: 20,
  diecastCar: 15,
  comicBook: 25,
  modelTrain: 80,
  watch: 120,
  headphones: 60,
  gameConsole: 180,
  monitor: 150,
  router: 40,
  printer: 80,
  dresser: 100,
  bookshelf: 70,
  nightstand: 50,
  coffeeTable: 90,
  ottoman: 45,
  bench: 55,
  bag: 50,
  belt: 20,
  sunglasses: 40,
  watchClothing: 100,
  jewelry: 80,
  boots: 70,
  level: 15,
  tapeMeasure: 10,
  socketSet: 50,
  angleGrinder: 80,
  circularSaw: 90,
  multimeter: 60,
  candleHolder: 15,
  plantStand: 35,
  wallArt: 40,
  throwPillow: 12,
  curtains: 30,
  bookend: 10,
  vinylRecord: 25,
  vintageToy: 35,
  sportsMemorabilia: 120,
  coin: 15,
  stamp: 10,
  poster: 20,
};

export const averageFixCosts = {
  // Typical repair or cleaning costs
  phone: 60,
  laptop: 100,
  speaker: 40,
  tv: 80,
  camera: 70,
  tablet: 50,
  chair: 20,
  table: 25,
  cabinet: 30,
  sofa: 60,
  bed: 50,
  desk: 40,
  jacket: 15,
  shoes: 20,
  shirt: 5,
  dress: 10,
  pants: 8,
  hat: 5,
  powerDrill: 40,
  wrench: 5,
  hammer: 5,
  saw: 10,
  screwdriver: 3,
  pliers: 5,
  lamp: 10,
  clock: 15,
  frame: 5,
  vase: 10,
  rug: 15,
  mirror: 15,
  actionFigure: 10,
  tradingCard: 5,
  diecastCar: 5,
  comicBook: 8,
  modelTrain: 30,
  watch: 40,
  headphones: 25,
  gameConsole: 50,
  monitor: 60,
  router: 20,
  printer: 40,
  dresser: 35,
  bookshelf: 25,
  nightstand: 20,
  coffeeTable: 30,
  ottoman: 15,
  bench: 20,
  bag: 15,
  belt: 8,
  sunglasses: 12,
  watchClothing: 35,
  jewelry: 20,
  boots: 25,
  level: 5,
  tapeMeasure: 3,
  socketSet: 20,
  angleGrinder: 35,
  circularSaw: 40,
  multimeter: 25,
  candleHolder: 5,
  plantStand: 15,
  wallArt: 10,
  throwPillow: 3,
  curtains: 12,
  bookend: 3,
  vinylRecord: 5,
  vintageToy: 10,
  sportsMemorabilia: 30,
  coin: 3,
  stamp: 2,
  poster: 5,
};

export const demandScores = {
  // 1-10: How fast it sells
  phone: 9,
  laptop: 8,
  speaker: 6,
  tv: 7,
  camera: 7,
  tablet: 8,
  chair: 5,
  table: 5,
  cabinet: 4,
  sofa: 6,
  bed: 4,
  desk: 5,
  jacket: 7,
  shoes: 8,
  shirt: 6,
  dress: 6,
  pants: 6,
  hat: 5,
  powerDrill: 8,
  wrench: 7,
  hammer: 6,
  saw: 7,
  screwdriver: 5,
  pliers: 6,
  lamp: 6,
  clock: 5,
  frame: 4,
  vase: 4,
  rug: 5,
  mirror: 6,
  actionFigure: 7,
  tradingCard: 8,
  diecastCar: 6,
  comicBook: 7,
  modelTrain: 5,
  watch: 8,
  headphones: 7,
  gameConsole: 9,
  monitor: 7,
  router: 6,
  printer: 5,
  dresser: 5,
  bookshelf: 5,
  nightstand: 5,
  coffeeTable: 6,
  ottoman: 5,
  bench: 5,
  bag: 8,
  belt: 6,
  sunglasses: 7,
  watchClothing: 8,
  jewelry: 7,
  boots: 8,
  level: 5,
  tapeMeasure: 4,
  socketSet: 7,
  angleGrinder: 7,
  circularSaw: 7,
  multimeter: 6,
  candleHolder: 4,
  plantStand: 4,
  wallArt: 5,
  throwPillow: 5,
  curtains: 5,
  bookend: 3,
  vinylRecord: 7,
  vintageToy: 6,
  sportsMemorabilia: 8,
  coin: 6,
  stamp: 5,
  poster: 6,
};

export const categoryToolkits = {
  electronics: ['Precision Screwdrivers', 'Isopropyl Alcohol', 'Microfiber Cloth', 'Multimeter'],
  furniture: ['Wood Glue', 'Sandpaper', 'Microfiber Cloth', 'Touch-up Markers'],
  clothing: ['Lint Roller', 'Fabric Shaver', 'Steamer', 'Stain Remover'],
  tools: ['WD-40', 'Steel Wool', 'Degreaser', 'Work Gloves'],
  decor: ['Glass Cleaner', 'Microfiber Cloth', 'Super Glue', 'Paint Brush'],
  collectibles: ['Soft Brush', 'Compressed Air', 'Card Sleeves', 'UV Display Case'],
};

export const categoryPlatforms = {
  electronics: [
    { name: 'eBay', strength: 'Global Reach', fee: '13%', shipping: 'High' },
    { name: 'FB Marketplace', strength: 'Local Cash', fee: '0%', shipping: 'None' },
    { name: 'Swappa', strength: 'Tech Focus', fee: 'Low', shipping: 'Med' },
  ],
  furniture: [
    { name: 'FB Marketplace', strength: 'Local Pickup', fee: '0%', shipping: 'None' },
    { name: 'OfferUp', strength: 'Quick Sales', fee: '0%', shipping: 'None' },
    { name: 'Chairish', strength: 'High End', fee: '30%', shipping: 'White Glove' },
  ],
  clothing: [
    { name: 'Poshmark', strength: 'Social Selling', fee: '20%', shipping: 'Easy' },
    { name: 'eBay', strength: 'International', fee: '13%', shipping: 'Med' },
    { name: 'Depop', strength: 'Vintage/Gen Z', fee: '10%', shipping: 'Med' },
  ],
  tools: [
    { name: 'FB Marketplace', strength: 'Local Trades', fee: '0%', shipping: 'None' },
    { name: 'Craigslist', strength: 'Old School', fee: '0%', shipping: 'None' },
    { name: 'eBay', strength: 'Parts/Small Tools', fee: '13%', shipping: 'High' },
  ],
  decor: [
    { name: 'Etsy', strength: 'Handmade/Vintage', fee: '6.5%', shipping: 'High' },
    { name: 'eBay', strength: 'Collectibility', fee: '13%', shipping: 'Med' },
    { name: 'FB Marketplace', strength: 'Fast Local', fee: '0%', shipping: 'None' },
  ],
  collectibles: [
    { name: 'eBay', strength: 'Max Value', fee: '13%', shipping: 'High' },
    { name: 'StockX', strength: 'Verified Only', fee: '10%', shipping: 'Easy' },
    { name: 'Heritage Auctions', strength: 'High Tier', fee: 'Var', shipping: 'Insured' },
  ],
};

export const typeMultipliers = {
  vintage: 1.2,
  modern: 1.0,
  damaged: 0.5,
  refurbished: 1.1,
};

export const conditionMultipliers = {
  'Cracked Screen': 0.4,
  'Battery Issues': 0.6,
  'Water Damage': 0.3,
  'No Power': 0.2,
  'Broken Buttons': 0.5,
  'Broken Keyboard': 0.5,
  'Overheating': 0.6,
  'Screen Flicker': 0.7,
  'Damaged Ports': 0.5,
  'No Sound': 0.6,
  'Connectivity Issues': 0.7,
  'Physical Damage': 0.5,
  'Distorted Audio': 0.6,
  'Power Failure': 0.4,
  'Screen Damage': 0.3,
  'Broken Remote': 0.5,
  'Color Distortion': 0.5,
  'Sound Issues': 0.6,
  'Lens Scratch': 0.6,
  'Battery Failure': 0.5,
  'Focus Problems': 0.5,
  'Memory Error': 0.6,
  'Shutter Issue': 0.5,
  'Battery Swollen': 0.4,
  'Charging Port Loose': 0.5,
  'Unresponsive': 0.3,
  'Broken Leg': 0.6,
  'Worn Fabric': 0.7,
  'Loose Joints': 0.6,
  'Scratched Surface': 0.7,
  'Missing Parts': 0.5,
  'Loose Legs': 0.6,
  'Water Stains': 0.6,
  'Wobbly': 0.5,
  'Chipped Edge': 0.7,
  'Broken Hinges': 0.5,
  'Missing Shelves': 0.6,
  'Stuck Drawer': 0.6,
  'Loose Door': 0.6,
  'Torn Upholstery': 0.5,
  'Sagging Cushions': 0.6,
  'Broken Springs': 0.4,
  'Stains': 0.6,
  'Faded Fabric': 0.7,
  'Broken Slats': 0.5,
  'Worn Mattress': 0.6,
  'Loose Screws': 0.7,
  'Squeaky': 0.8,
  'Stained Headboard': 0.6,
  'Scratched Top': 0.7,
  'Broken Drawer': 0.6,
  'Water Damage': 0.4,
  'Chipped Finish': 0.7,
  'Torn Sleeve': 0.6,
  'Missing Buttons': 0.7,
  'Stained': 0.6,
  'Broken Zipper': 0.5,
  'Faded Color': 0.7,
  'Worn Soles': 0.5,
  'Loose Stitching': 0.6,
  'Scuffed Surface': 0.7,
  'Broken Laces': 0.6,
  'Torn Collar': 0.6,
  'Loose Threads': 0.7,
  'Torn Hem': 0.6,
  'Missing Zipper': 0.5,
  'Loose Seams': 0.7,
  'Torn Knee': 0.6,
  'Broken Zipper': 0.5,
  'Loose Waistband': 0.6,
  'Sweat Stains': 0.7,
  'Frayed Brim': 0.6,
  'Missing Strap': 0.5,
  'Dull Bit': 0.6,
  'Motor Issues': 0.4,
  'Battery Problems': 0.5,
  'Chuck Slipping': 0.6,
  'Broken Trigger': 0.4,
  'Rusty': 0.5,
  'Loose Grip': 0.6,
  'Bent': 0.6,
  'Worn Teeth': 0.6,
  'Stuck Adjustment': 0.6,
  'Loose Head': 0.6,
  'Worn Handle': 0.7,
  'Chipped Face': 0.6,
  'Bent Claw': 0.6,
  'Dull Blade': 0.6,
  'Bent Teeth': 0.6,
  'Broken Handle': 0.5,
  'Loose Guard': 0.6,
  'Stripped Tip': 0.6,
  'Bent Shaft': 0.6,
  'Worn Grip': 0.7,
  'Loose Joint': 0.6,
  'Bent Jaws': 0.6,
  'Spring Broken': 0.5,
  'Broken Bulb': 0.7,
  'Damaged Shade': 0.6,
  'Faulty Wiring': 0.5,
  'Loose Switch': 0.6,
  'Rusty Base': 0.5,
  'Not Working': 0.4,
  'Missing Hands': 0.5,
  'Cracked Glass': 0.4,
  'Dead Battery': 0.5,
  'Damaged Frame': 0.6,
  'Broken Glass': 0.4,
  'Loose Backing': 0.6,
  'Bent Edge': 0.6,
  'Cracked': 0.4,
  'Chipped Rim': 0.6,
  'Broken Handle': 0.5,
  'Faded Paint': 0.7,
  'Frayed Edges': 0.7,
  'Torn Fibers': 0.6,
  'Odor': 0.6,
  'Chipped Frame': 0.6,
  'Hazy Surface': 0.6,
  'Loose Hanging Wire': 0.6,
  'Loose/No Box': 0.5,
  'Missing Accessories': 0.7,
  'Paint Wear': 0.6,
  'Broken Joint': 0.4,
  'Yellowed Plastic': 0.5,
  'Heavy Crease': 0.3,
  'Whiting on Edges': 0.6,
  'Surface Scratches': 0.7,
  'Off-Center Cut': 0.5,
  'Paint Chips': 0.7,
  'Bent Axle': 0.5,
  'Missing Wheels': 0.3,
  'Scratched Windshield': 0.6,
  'Rusty Base': 0.4,
  'Torn Cover': 0.4,
  'Yellowed Pages': 0.6,
  'Bent Corners': 0.7,
  'Loose Staples': 0.5,
  'Writing/Ink Marks': 0.4,
  'Derailed/Bent Frame': 0.4,
  'Missing Coupler': 0.6,
  'Motor Not Running': 0.3,
  'Scratched Paint': 0.7,
  'Broken Detail Part': 0.6,
  'Dead Battery': 0.5,
  'Scratched Crystal': 0.6,
  'Broken Band': 0.5,
  'Not Working': 0.3,
  'Broken Cable': 0.5,
  'Cracked Headband': 0.4,
  'One Side Dead': 0.4,
  'Loose Connection': 0.6,
  'Disc Drive Broken': 0.4,
  'Controller Issues': 0.6,
  'HDMI Port Damaged': 0.4,
  'Dead Pixels': 0.7,
  'No Display': 0.3,
  'Flickering Screen': 0.5,
  'No WiFi Signal': 0.4,
  'Damaged Antenna': 0.5,
  'Ports Not Working': 0.4,
  'Paper Jams': 0.6,
  'Ink Issues': 0.5,
  'Not Printing': 0.3,
  'Error Codes': 0.4,
  'Damaged Tray': 0.6,
  'Broken Drawers': 0.5,
  'Loose Handles': 0.6,
  'Loose Shelves': 0.6,
  'Missing Back Panel': 0.5,
  'Chipped Edges': 0.7,
  'Scratched Top': 0.7,
  'Missing Hardware': 0.5,
  'Water Rings': 0.6,
  'Torn Fabric': 0.5,
  'Worn Cushion': 0.6,
  'Broken Legs': 0.4,
  'Worn Seat': 0.6,
  'Broken Slats': 0.5,
  'Torn Strap': 0.5,
  'Worn Lining': 0.6,
  'Cracked Leather': 0.5,
  'Holes Worn': 0.6,
  'Scratched Lenses': 0.4,
  'Broken Frame': 0.3,
  'Missing Lenses': 0.2,
  'Loose Hinges': 0.6,
  'Scratched Face': 0.6,
  'Missing Links': 0.6,
  'Tarnished': 0.6,
  'Missing Stones': 0.4,
  'Broken Clasp': 0.5,
  'Loose Setting': 0.6,
  'Torn Lining': 0.5,
  'Bubble Off': 0.4,
  'Missing End Caps': 0.5,
  'Broken Lock': 0.5,
  'Torn Tape': 0.3,
  'Stuck': 0.4,
  'Missing End Hook': 0.5,
  'Missing Sockets': 0.5,
  'Broken Ratchet': 0.4,
  'Dull Disc': 0.6,
  'Broken Guard': 0.5,
  'Worn Brushes': 0.6,
  'Worn Base': 0.6,
  'Broken Display': 0.3,
  'Faulty Probes': 0.5,
  'Not Reading': 0.4,
  'Damaged Case': 0.6,
  'Tarnished': 0.6,
  'Missing Base': 0.5,
  'Missing Shelf': 0.5,
  'Bent Legs': 0.5,
  'Torn': 0.4,
  'Missing Hooks': 0.6,
  'Loose Hems': 0.6,
  'Scratches': 0.6,
  'Warped': 0.4,
  'Worn Grooves': 0.5,
  'Missing Sleeve': 0.6,
  'Missing Parts': 0.5,
  'Broken': 0.3,
  'No Box': 0.5,
  'Missing Signature': 0.4,
  'Discolored': 0.5,
  'Missing Perforations': 0.5,
  'Creamed': 0.4,
  'Creased': 0.5,
  'Tape Marks': 0.5,
  default: 0.7,
};
